/**
 * Migration: Create free_trial_codes table
 *
 * This table stores free trial codes that can be generated by admins
 * and used by users to access free trials.
 */

export const up = async function (knex) {
  await knex.schema.createTable("free_trial_codes", function (table) {
    // Primary key
    table.uuid("uuid").primary().defaultTo(knex.raw("gen_random_uuid()"));

    // Code (4-digit alphanumeric)
    table
      .string("code")
      .notNullable()
      .unique()
      .comment("4-digit alphanumeric code for free trial access");

    // Status
    table
      .integer("status")
      .defaultTo(1)
      .comment("1 = active/unused, 0 = inactive/used");

    // User who used the code (nullable)
    table
      .uuid("used_by_user_uuid")
      .nullable()
      .comment("UUID of the user who used this code");

    table
      .foreign("used_by_user_uuid")
      .references("uuid")
      .inTable("users")
      .onDelete("SET NULL")
      .onUpdate("CASCADE");

    // Platform account associated with code usage (nullable)
    table
      .uuid("used_by_platform_account_uuid")
      .nullable()
      .comment("UUID of the platform account created using this code");

    table
      .foreign("used_by_platform_account_uuid")
      .references("uuid")
      .inTable("platform_accounts")
      .onDelete("SET NULL")
      .onUpdate("CASCADE");

    // Common metadata
    table.timestamp("created_at").defaultTo(knex.fn.now());
    table.timestamp("updated_at").defaultTo(knex.fn.now());

    // Helpful indexes
    table.index(["code"]);
    table.index(["status"]);
    table.index(["used_by_user_uuid"]);
    table.index(["used_by_platform_account_uuid"]);
  });
};

export const down = async function (knex) {
  await knex.schema.dropTable("free_trial_codes");
};
